# Generated by Django 5.1.5 on 2025-01-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cartorderitem_original_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitem',
            name='original_total',
        ),
    ]
