# Generated by Django 5.1.5 on 2025-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_notification_user_alter_notification_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='paypal_session_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
