# Generated by Django 5.1.5 on 2025-02-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_cartorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
