# Generated by Django 5.1.5 on 2025-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_color_color_code_alter_color_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='stripe', max_length=100),
        ),
    ]
