# Generated by Django 5.1.5 on 2025-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_cartorder_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='oid',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='oid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
