# Generated by Django 5.1.5 on 2025-05-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_cartorder_oid_alter_cartorderitem_oid'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'Order'), ('vendor', 'Vendor'), ('system', 'System'), ('account', 'Account')], default='system', max_length=20),
        ),
    ]
