# Generated by Django 5.1.5 on 2025-05-04 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_field_lengths'),
        ('store', '0025_notification_type'),
    ]

    operations = [
    ]
