# Generated by Django 5.1.5 on 2025-05-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_merge_0025_alter_field_lengths_0025_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Service fee percentage applied to orders (e.g., 5.00 = 5%)', max_digits=5)),
                ('currency_symbol', models.CharField(default='$', help_text='Currency symbol to display (e.g., $, €, £)', max_length=10)),
                ('currency_code', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=10)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
